# _config.yml (repo root)
url: "https://mpincus.github.io"            # your GitHub Pages domain
baseurl: "/SwingScannerWatchlist-GPT"       # repo name prefixed with a slash
include:
  - watchlist.csv
  - combined_watchlist.csv                  # add any others you want published
# (make sure you don't also "exclude" these anywhere)
