name: Backtest Quality Trades

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * 1-5"   # 10:00 PM UTC, weekdays

permissions:
  contents: write

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas numpy

      - name: Sanity check inputs
        run: |
          pwd && git rev-parse --abbrev-ref HEAD
          ls -la
          ls -la data || echo "NO data dir"
          test -f data/combined.csv && echo "FOUND data/combined.csv" || (echo "MISSING data/combined.csv" && exit 1)

      - name: Run backtest
        run: |
          set -e
          python -u scripts/backtest_quality.py
          echo "--- AFTER RUN ---"
          ls -la data || true
          head -n 5 data/quality_trades.csv || (echo "quality_trades.csv missing"; exit 1)
          head -n 5 data/quality_stats.csv  || (echo "quality_stats.csv missing";  exit 1)

      - name: Save results into docs
        run: |
          mkdir -p docs
          cp data/quality_trades.csv docs/
          cp data/quality_stats.csv docs/

      - name: Commit results (safe)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/quality_trades.csv data/quality_stats.csv docs/quality_trades.csv docs/quality_stats.csv
          git commit -m "Update backtest results [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main