name: Fetch OHLCV Data

on:
  schedule:
    # 22:30 UTC ≈ 6:30pm ET, Mon–Fri
    - cron: "30 22 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate CSVs
        run: python scripts/fetch_data.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update OHLCV data CSVs"
          file_pattern: data/*.csv