name: Copy CSVs to docs

on:
  schedule:
    # Weekdays at 21:40 UTC (after US market close). Adjust if you like.
    - cron: '40 21 * * 1-5'

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to copy from'
        default: 'main'
        required: true

permissions:
  contents: write

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Diagnose repo state
        run: |
          set -euo pipefail
          echo "Commit: $(git rev-parse --short HEAD)"
          echo "Top-level:"
          ls -la
          echo "data/:"
          ls -la data || true
          echo "docs/:"
          ls -la docs || true

      - name: Verify data directory exists
        run: |
          set -euo pipefail
          test -d data || (echo "ERROR: data/ directory not found" && exit 1)
          echo "Files in data/:"
          ls -lh data

      - name: Copy all files into docs with logging
        run: |
          set -euo pipefail
          mkdir -p docs
          cp -v data/* docs/ || true
          echo "docs/ after copy:"
          ls -la docs

      - name: Git add and commit (force include)
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A docs/
          git status --porcelain
          git commit -m "Copy all data/ files to docs (manual)" || echo "No changes to commit"

      - name: Push
        run: |
          set -euo pipefail
          git push