name: Build Quality Signals

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify inputs
        run: |
          test -f data/combined.csv || (echo "missing: data/combined.csv" && exit 1)
          test -f data/signals.csv  || (echo "missing: data/signals.csv" && exit 1)

      - name: Run quality scan
        run: python scripts/quality_scan.py

      - name: Verify output
        run: |
          test -f data/signals_quality.csv || (echo "missing: data/signals_quality.csv" && exit 1)
          head -n 5 data/signals_quality.csv || true

      - name: Copy to docs
        run: |
          mkdir -p docs
          cp -vf data/signals_quality.csv docs/signals_quality.csv
          ls -la docs

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Publish signals_quality.csv"
          file_pattern: |
            docs/signals_quality.csv
            data/signals_quality.csv

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: signals-quality
          path: data/signals_quality.csv